backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'water-agreement'
    label: 'Water Agreement'
    folder: 'content/water'
    create: false
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'past'
    label: 'Past'
    folder: 'content/past'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'present'
    label: 'Present'
    folder: 'content/present'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'future'
    label: 'Future'
    folder: 'content/future'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'landing'
    label: 'Landing'
    folder: 'content/landing'
    create: false
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Category', name: 'category', widget: 'string' }
    - { label: 'MapText', name: 'maptext', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: false
    fields:
      - { label: 'Description', name: 'description', widget: 'text' }
  - name: 'profiles'
    label: 'Profiles'
    folder: 'content/about/profiles'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Picture', name: 'picture', widget: 'image', media_folder: "/static/images/profilepics" }
      - { label: 'Description', name: 'description', widget: 'string' }