backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'landing'
    label: 'Landing'
    folder: 'content/landing'
    create: false
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Category', name: 'category', widget: 'string' }
    - { label: 'MapText', name: 'maptext', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'past'
    label: 'Past'
    folder: 'content/past'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Image'
        name: 'gallery'
        widget: 'list'
        allow_add: true
        required: false
        fields:
          - { label: 'Image', name: 'img', widget: 'image'}
          - { label: 'Caption', name: 'caption', widget: 'string'}
  - name: 'present'
    label: 'Present'
    folder: 'content/present'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Image'
        name: 'gallery'
        widget: 'list'
        allow_add: true
        required: false
        fields:
          - { label: 'Image', name: 'img', widget: 'image'}
          - { label: 'Caption', name: 'caption', widget: 'string'}
  - name: 'future'
    label: 'Future'
    folder: 'content/future'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'X', name: 'x', widget: 'string' }
      - { label: 'Y', name: 'y', widget: 'string' }
      - { label: 'Audio', name: 'audio', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Image'
        name: 'gallery'
        widget: 'list'
        allow_add: true
        required: false
        fields:
          - { label: 'Image', name: 'img', widget: 'image'}
          - { label: 'Caption', name: 'caption', widget: 'string'}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: 'about'
        label: 'About'
        folder: 'content/about'
        file: 'content/about/_index.md'
        create: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
      - name: 'get-involved'
        label: 'Get Involved'
        folder: 'content/get-involved'
        file: 'content/get-involved/_index.md'
        create: false
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown'}
          - { label: 'Connect', name: 'connect', widget: 'markdown'}
          - { label: 'Connect Hashtags', name: 'hashtags', widget: 'markdown'}
          - { label: 'Re Imagine', name: 'reimagine', widget: 'markdown'}
      - name: 'reclaim'
        label: 'Reclaim'
        folder: 'content/get-involved'
        file: 'content/get-involved/reclaim.md'
        create: false
        fields:
          - label: 'Content'
            name: 'content'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Header', name: 'header', widget: 'string'}
              - { label: 'Light Background', name: 'light', widget: 'boolean', required: false }
              - { label: 'Text', name: 'text', widget: 'markdown'}
      - name: 'unlearn'
        label: 'Unlearn'
        folder: 'content/get-involved'
        file: 'content/get-involved/unlearn.md'
        fields:
          - label: 'Reading List'
            name: 'books'
            widget: 'list'
            fields:
              - { label: Book Image', name: 'book', widget: 'image'}
              - { label: 'Book Link', name: 'link', widget: 'string'}
      - name: 'act'
        label: 'Act'
        folder: 'content/get-involved'
        file: 'content/get-involved/act.md'
        create: false
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown'}
          - label: 'At Home Accordion'
            name: 'home'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Accordion Header', name: 'header', widget: 'string'}
              - { label: 'Accordion Text', name: 'text', widget: 'markdown'}
          - label: 'In Community Accordion'
            name: 'community'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Accordion Header', name: 'header', widget: 'string'}
              - { label: 'Accordion Text', name: 'text', widget: 'markdown'}
      - name: 'media'
        label: 'Media'
        folder: 'content/media'
        file: 'content/media/_index.md'
        create: false
        fields:
          - label: 'Media Column Left'
            name: 'colleft'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string'}
              - { label: 'Description', name: 'description', widget: 'markdown'}
              - { label: 'Image', name: 'image', widget: 'image', required: false}
              - label: 'Link'
                name: 'link'
                widget: 'list'
                allow_add: true
                fields:
                  - { label: 'Link Label', name: 'label', widget: 'string'}
                  - { label: 'Link Url', name: 'url', widget: 'string'}
          - label: 'Media Column Right'
            name: 'colright'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string'}
              - { label: 'Description', name: 'description', widget: 'markdown'}
              - { label: 'Image', name: 'image', widget: 'image', required: false}
              - label: 'Link'
                name: 'link'
                widget: 'list'
                allow_add: true
                fields:
                  - { label: 'Link Label', name: 'label', widget: 'string'}
                  - { label: 'Link Url', name: 'url', widget: 'string'}
      - name: 'en espa単ol'
        label: 'En Espa単ol'
        folder: 'content/en-espa単ol'
        file: 'content/en-espa単ol/_index.md'
        create: false
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown'}
          - label: 'Audio Files'
            name: 'content'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string'}
              - { label: 'Audio File Name', name: 'audiofile', widget: 'string'}
  - name: 'profiles'
    label: 'Profiles'
    folder: 'content/about/profiles'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Picture', name: 'picture', widget: 'image' }
      - { label: 'Intention', name: 'intention', widget: 'markdown' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
      - { label: 'LinkedIn', name: 'linkedin', widget: 'string', required: false}
      - { label: 'websiteurl', name: 'websiteurl', widget: 'string', required: false}
  - name: 'water-agreement'
    label: 'Water Agreement'
    folder: 'content/water'
    create: false
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }